import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Enhanced Category Seed with Google Business Profile Categories
 * This seed creates an expanded category hierarchy aligned with Google Business Profile
 * Total: 227+ categories across 10 main groups
 */

interface CategoryData {
  slug: string;
  name: string;
  nameFr: string;
  nameEn: string;
  nameDe?: string;
  description?: string;
  icon: string;
  color?: string;
  googleBusinessCategory: string;
  googleTypes?: string[];
  children?: CategoryData[];
}

const categories: CategoryData[] = [
  {
    slug: 'alimentation',
    name: 'Alimentation',
    nameFr: 'Alimentation',
    nameEn: 'Food & Dining',
    nameDe: 'Essen & Trinken',
    description: 'Restaurants, cafés, boulangeries et commerces alimentaires',
    icon: '🍽️',
    color: '#F59E0B',
    googleBusinessCategory: 'Food & Dining',
    children: [
      {
        slug: 'afghani-restaurant',
        name: 'Restaurant afghani',
        nameFr: 'Restaurant afghani',
        nameEn: 'Afghani restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Afghani restaurant',
      },
      {
        slug: 'african-restaurant',
        name: 'Restaurant african',
        nameFr: 'Restaurant african',
        nameEn: 'African restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'African restaurant',
      },
      {
        slug: 'alsace-restaurant',
        name: 'Restaurant alsace',
        nameFr: 'Restaurant alsace',
        nameEn: 'Alsace restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Alsace restaurant',
      },
      {
        slug: 'american-restaurant',
        name: 'Restaurant american',
        nameFr: 'Restaurant american',
        nameEn: 'American restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'American restaurant',
      },
      {
        slug: 'anago-restaurant',
        name: 'Restaurant anago',
        nameFr: 'Restaurant anago',
        nameEn: 'Anago restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Anago restaurant',
      },
      {
        slug: 'andalusian-restaurant',
        name: 'Restaurant andalusian',
        nameFr: 'Restaurant andalusian',
        nameEn: 'Andalusian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Andalusian restaurant',
      },
      {
        slug: 'angler-fish-restaurant',
        name: 'Restaurant angler fish',
        nameFr: 'Restaurant angler fish',
        nameEn: 'Angler fish restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Angler fish restaurant',
      },
      {
        slug: 'anhui-restaurant',
        name: 'Restaurant anhui',
        nameFr: 'Restaurant anhui',
        nameEn: 'Anhui restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Anhui restaurant',
      },
      {
        slug: 'argentinian-restaurant',
        name: 'Restaurant argentinian',
        nameFr: 'Restaurant argentinian',
        nameEn: 'Argentinian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Argentinian restaurant',
      },
      {
        slug: 'armenian-restaurant',
        name: 'Restaurant armenian',
        nameFr: 'Restaurant armenian',
        nameEn: 'Armenian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Armenian restaurant',
      },
      {
        slug: 'asian-fusion-restaurant',
        name: 'Restaurant asian fusion',
        nameFr: 'Restaurant asian fusion',
        nameEn: 'Asian fusion restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Asian fusion restaurant',
      },
      {
        slug: 'asian-restaurant',
        name: 'Restaurant asian',
        nameFr: 'Restaurant asian',
        nameEn: 'Asian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Asian restaurant',
      },
      {
        slug: 'asturian-restaurant',
        name: 'Restaurant asturian',
        nameFr: 'Restaurant asturian',
        nameEn: 'Asturian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Asturian restaurant',
      },
      {
        slug: 'australian-restaurant',
        name: 'Restaurant australian',
        nameFr: 'Restaurant australian',
        nameEn: 'Australian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Australian restaurant',
      },
      {
        slug: 'austrian-restaurant',
        name: 'Restaurant austrian',
        nameFr: 'Restaurant austrian',
        nameEn: 'Austrian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Austrian restaurant',
      },
      {
        slug: 'authentic-japanese-restaurant',
        name: 'Restaurant authentic japanese',
        nameFr: 'Restaurant authentic japanese',
        nameEn: 'Authentic Japanese restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Authentic Japanese restaurant',
      },
      {
        slug: 'baden-restaurant',
        name: 'Restaurant baden',
        nameFr: 'Restaurant baden',
        nameEn: 'Baden restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Baden restaurant',
      },
      {
        slug: 'bakso-restaurant',
        name: 'Restaurant bakso',
        nameFr: 'Restaurant bakso',
        nameEn: 'Bakso restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Bakso restaurant',
      },
      {
        slug: 'balinese-restaurant',
        name: 'Restaurant balinese',
        nameFr: 'Restaurant balinese',
        nameEn: 'Balinese restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Balinese restaurant',
      },
      {
        slug: 'bangladeshi-restaurant',
        name: 'Restaurant bangladeshi',
        nameFr: 'Restaurant bangladeshi',
        nameEn: 'Bangladeshi restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Bangladeshi restaurant',
      },
      {
        slug: 'bar-restaurant-furniture-store',
        name: 'Restaurant bar furniture store',
        nameFr: 'Restaurant bar furniture store',
        nameEn: 'Bar restaurant furniture store',
        icon: '🍽️',
        googleBusinessCategory: 'Bar restaurant furniture store',
      },
      {
        slug: 'barbecue-restaurant',
        name: 'Restaurant barbecue',
        nameFr: 'Restaurant barbecue',
        nameEn: 'Barbecue restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Barbecue restaurant',
      },
      {
        slug: 'basque-restaurant',
        name: 'Restaurant basque',
        nameFr: 'Restaurant basque',
        nameEn: 'Basque restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Basque restaurant',
      },
      {
        slug: 'batak-restaurant',
        name: 'Restaurant batak',
        nameFr: 'Restaurant batak',
        nameEn: 'Batak restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Batak restaurant',
      },
      {
        slug: 'bavarian-restaurant',
        name: 'Restaurant bavarian',
        nameFr: 'Restaurant bavarian',
        nameEn: 'Bavarian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Bavarian restaurant',
      },
      {
        slug: 'belgian-restaurant',
        name: 'Restaurant belgian',
        nameFr: 'Restaurant belgian',
        nameEn: 'Belgian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Belgian restaurant',
      },
      {
        slug: 'berry-restaurant',
        name: 'Restaurant berry',
        nameFr: 'Restaurant berry',
        nameEn: 'Berry restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Berry restaurant',
      },
      {
        slug: 'betawi-restaurant',
        name: 'Restaurant betawi',
        nameFr: 'Restaurant betawi',
        nameEn: 'Betawi restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Betawi restaurant',
      },
      {
        slug: 'biryani-restaurant',
        name: 'Restaurant biryani',
        nameFr: 'Restaurant biryani',
        nameEn: 'Biryani restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Biryani restaurant',
      },
      {
        slug: 'brazilian-restaurant',
        name: 'Restaurant brazilian',
        nameFr: 'Restaurant brazilian',
        nameEn: 'Brazilian restaurant',
        icon: '🍽️',
        googleBusinessCategory: 'Brazilian restaurant',
      },
    ],
  },
  {
    slug: 'sante',
    name: 'Santé',
    nameFr: 'Santé',
    nameEn: 'Health & Medical',
    nameDe: 'Gesundheit',
    description: 'Services médicaux, pharmacies et soins de santé',
    icon: '⚕️',
    color: '#10B981',
    googleBusinessCategory: 'Health & Medical',
    children: [
      {
        slug: 'pharmacy',
        name: 'Pharmacie',
        nameFr: 'Pharmacie',
        nameEn: 'Pharmacy',
        icon: '⚕️',
        googleBusinessCategory: 'Pharmacy',
      },
      {
        slug: 'doctor',
        name: 'Médecin',
        nameFr: 'Médecin',
        nameEn: 'Doctor',
        icon: '⚕️',
        googleBusinessCategory: 'Doctor',
      },
      {
        slug: 'dentist',
        name: 'Dentiste',
        nameFr: 'Dentiste',
        nameEn: 'Dentist',
        icon: '⚕️',
        googleBusinessCategory: 'Dentist',
      },
      {
        slug: 'dental-clinic',
        name: 'Clinique dentaire',
        nameFr: 'Clinique dentaire',
        nameEn: 'Dental clinic',
        icon: '⚕️',
        googleBusinessCategory: 'Dental clinic',
      },
      {
        slug: 'hospital',
        name: 'Hôpital',
        nameFr: 'Hôpital',
        nameEn: 'Hospital',
        icon: '⚕️',
        googleBusinessCategory: 'Hospital',
      },
      {
        slug: 'medical-clinic',
        name: 'Clinique médicale',
        nameFr: 'Clinique médicale',
        nameEn: 'Medical clinic',
        icon: '⚕️',
        googleBusinessCategory: 'Medical clinic',
      },
      {
        slug: 'urgent-care-center',
        name: 'Urgent care center',
        nameFr: 'Urgent care center',
        nameEn: 'Urgent care center',
        icon: '⚕️',
        googleBusinessCategory: 'Urgent care center',
      },
      {
        slug: 'physical-therapist',
        name: 'Physical therapist',
        nameFr: 'Physical therapist',
        nameEn: 'Physical therapist',
        icon: '⚕️',
        googleBusinessCategory: 'Physical therapist',
      },
      {
        slug: 'chiropractor',
        name: 'Chiropractor',
        nameFr: 'Chiropractor',
        nameEn: 'Chiropractor',
        icon: '⚕️',
        googleBusinessCategory: 'Chiropractor',
      },
      {
        slug: 'acupuncturist',
        name: 'Acupuncturist',
        nameFr: 'Acupuncturist',
        nameEn: 'Acupuncturist',
        icon: '⚕️',
        googleBusinessCategory: 'Acupuncturist',
      },
      {
        slug: 'optometrist',
        name: 'Optometrist',
        nameFr: 'Optometrist',
        nameEn: 'Optometrist',
        icon: '⚕️',
        googleBusinessCategory: 'Optometrist',
      },
      {
        slug: 'pediatrician',
        name: 'Pediatrician',
        nameFr: 'Pediatrician',
        nameEn: 'Pediatrician',
        icon: '⚕️',
        googleBusinessCategory: 'Pediatrician',
      },
      {
        slug: 'dermatologist',
        name: 'Dermatologist',
        nameFr: 'Dermatologist',
        nameEn: 'Dermatologist',
        icon: '⚕️',
        googleBusinessCategory: 'Dermatologist',
      },
    ],
  },
  {
    slug: 'commerces',
    name: 'Commerces',
    nameFr: 'Commerces',
    nameEn: 'Retail & Shopping',
    nameDe: 'Einzelhandel',
    description: 'Magasins et boutiques',
    icon: '🛍️',
    color: '#8B5CF6',
    googleBusinessCategory: 'Retail & Shopping',
    children: [
      {
        slug: 'clothing-store',
        name: 'Magasin de vêtements',
        nameFr: 'Magasin de vêtements',
        nameEn: 'Clothing store',
        icon: '🛍️',
        googleBusinessCategory: 'Clothing store',
      },
      {
        slug: 'shoe-store',
        name: 'Magasin de chaussures',
        nameFr: 'Magasin de chaussures',
        nameEn: 'Shoe store',
        icon: '🛍️',
        googleBusinessCategory: 'Shoe store',
      },
      {
        slug: 'jewelry-store',
        name: 'Bijouterie',
        nameFr: 'Bijouterie',
        nameEn: 'Jewelry store',
        icon: '🛍️',
        googleBusinessCategory: 'Jewelry store',
      },
      {
        slug: 'book-store',
        name: 'Librairie',
        nameFr: 'Librairie',
        nameEn: 'Book store',
        icon: '🛍️',
        googleBusinessCategory: 'Book store',
      },
      {
        slug: 'electronics-store',
        name: 'Magasin d\'électronique',
        nameFr: 'Magasin d\'électronique',
        nameEn: 'Electronics store',
        icon: '🛍️',
        googleBusinessCategory: 'Electronics store',
      },
      {
        slug: 'furniture-store',
        name: 'Magasin de meubles',
        nameFr: 'Magasin de meubles',
        nameEn: 'Furniture store',
        icon: '🛍️',
        googleBusinessCategory: 'Furniture store',
      },
      {
        slug: 'home-goods-store',
        name: 'Home goods store',
        nameFr: 'Home goods store',
        nameEn: 'Home goods store',
        icon: '🛍️',
        googleBusinessCategory: 'Home goods store',
      },
      {
        slug: 'supermarket',
        name: 'Supermarché',
        nameFr: 'Supermarché',
        nameEn: 'Supermarket',
        icon: '🛍️',
        googleBusinessCategory: 'Supermarket',
      },
      {
        slug: 'grocery-store',
        name: 'Épicerie',
        nameFr: 'Épicerie',
        nameEn: 'Grocery store',
        icon: '🛍️',
        googleBusinessCategory: 'Grocery store',
      },
      {
        slug: 'convenience-store',
        name: 'Supérette',
        nameFr: 'Supérette',
        nameEn: 'Convenience store',
        icon: '🛍️',
        googleBusinessCategory: 'Convenience store',
      },
      {
        slug: 'department-store',
        name: 'Department store',
        nameFr: 'Department store',
        nameEn: 'Department store',
        icon: '🛍️',
        googleBusinessCategory: 'Department store',
      },
      {
        slug: 'shopping-mall',
        name: 'Shopping mall',
        nameFr: 'Shopping mall',
        nameEn: 'Shopping mall',
        icon: '🛍️',
        googleBusinessCategory: 'Shopping mall',
      },
      {
        slug: 'gift-shop',
        name: 'Gift shop',
        nameFr: 'Gift shop',
        nameEn: 'Gift shop',
        icon: '🛍️',
        googleBusinessCategory: 'Gift shop',
      },
      {
        slug: 'toy-store',
        name: 'Toy store',
        nameFr: 'Toy store',
        nameEn: 'Toy store',
        icon: '🛍️',
        googleBusinessCategory: 'Toy store',
      },
      {
        slug: 'sporting-goods-store',
        name: 'Sporting goods store',
        nameFr: 'Sporting goods store',
        nameEn: 'Sporting goods store',
        icon: '🛍️',
        googleBusinessCategory: 'Sporting goods store',
      },
      {
        slug: 'pet-store',
        name: 'Pet store',
        nameFr: 'Pet store',
        nameEn: 'Pet store',
        icon: '🛍️',
        googleBusinessCategory: 'Pet store',
      },
      {
        slug: 'florist',
        name: 'Florist',
        nameFr: 'Florist',
        nameEn: 'Florist',
        icon: '🛍️',
        googleBusinessCategory: 'Florist',
      },
      {
        slug: 'hardware-store',
        name: 'Hardware store',
        nameFr: 'Hardware store',
        nameEn: 'Hardware store',
        icon: '🛍️',
        googleBusinessCategory: 'Hardware store',
      },
      {
        slug: 'garden-center',
        name: 'Garden center',
        nameFr: 'Garden center',
        nameEn: 'Garden center',
        icon: '🛍️',
        googleBusinessCategory: 'Garden center',
      },
    ],
  },
  {
    slug: 'services',
    name: 'Services',
    nameFr: 'Services',
    nameEn: 'Services',
    nameDe: 'Dienstleistungen',
    description: 'Services professionnels et artisans',
    icon: '🔧',
    color: '#3B82F6',
    googleBusinessCategory: 'Services',
    children: [
      {
        slug: 'plumber',
        name: 'Plombier',
        nameFr: 'Plombier',
        nameEn: 'Plumber',
        icon: '🔧',
        googleBusinessCategory: 'Plumber',
      },
      {
        slug: 'electrician',
        name: 'Électricien',
        nameFr: 'Électricien',
        nameEn: 'Electrician',
        icon: '🔧',
        googleBusinessCategory: 'Electrician',
      },
      {
        slug: 'carpenter',
        name: 'Menuisier',
        nameFr: 'Menuisier',
        nameEn: 'Carpenter',
        icon: '🔧',
        googleBusinessCategory: 'Carpenter',
      },
      {
        slug: 'painter',
        name: 'Peintre',
        nameFr: 'Peintre',
        nameEn: 'Painter',
        icon: '🔧',
        googleBusinessCategory: 'Painter',
      },
      {
        slug: 'hvac-contractor',
        name: 'HVAC contractor',
        nameFr: 'HVAC contractor',
        nameEn: 'HVAC contractor',
        icon: '🔧',
        googleBusinessCategory: 'HVAC contractor',
      },
      {
        slug: 'general-contractor',
        name: 'General contractor',
        nameFr: 'General contractor',
        nameEn: 'General contractor',
        icon: '🔧',
        googleBusinessCategory: 'General contractor',
      },
      {
        slug: 'handyman',
        name: 'Handyman',
        nameFr: 'Handyman',
        nameEn: 'Handyman',
        icon: '🔧',
        googleBusinessCategory: 'Handyman',
      },
      {
        slug: 'locksmith',
        name: 'Serrurier',
        nameFr: 'Serrurier',
        nameEn: 'Locksmith',
        icon: '🔧',
        googleBusinessCategory: 'Locksmith',
      },
      {
        slug: 'landscaper',
        name: 'Paysagiste',
        nameFr: 'Paysagiste',
        nameEn: 'Landscaper',
        icon: '🔧',
        googleBusinessCategory: 'Landscaper',
      },
      {
        slug: 'gardener',
        name: 'Jardinier',
        nameFr: 'Jardinier',
        nameEn: 'Gardener',
        icon: '🔧',
        googleBusinessCategory: 'Gardener',
      },
      {
        slug: 'pest-control-service',
        name: 'Pest control service',
        nameFr: 'Pest control service',
        nameEn: 'Pest control service',
        icon: '🔧',
        googleBusinessCategory: 'Pest control service',
      },
      {
        slug: 'moving-company',
        name: 'Moving company',
        nameFr: 'Moving company',
        nameEn: 'Moving company',
        icon: '🔧',
        googleBusinessCategory: 'Moving company',
      },
      {
        slug: 'storage-facility',
        name: 'Storage facility',
        nameFr: 'Storage facility',
        nameEn: 'Storage facility',
        icon: '🔧',
        googleBusinessCategory: 'Storage facility',
      },
      {
        slug: 'laundry-service',
        name: 'Laundry service',
        nameFr: 'Laundry service',
        nameEn: 'Laundry service',
        icon: '🔧',
        googleBusinessCategory: 'Laundry service',
      },
      {
        slug: 'dry-cleaner',
        name: 'Dry cleaner',
        nameFr: 'Dry cleaner',
        nameEn: 'Dry cleaner',
        icon: '🔧',
        googleBusinessCategory: 'Dry cleaner',
      },
      {
        slug: 'tailor',
        name: 'Tailor',
        nameFr: 'Tailor',
        nameEn: 'Tailor',
        icon: '🔧',
        googleBusinessCategory: 'Tailor',
      },
      {
        slug: 'shoe-repair-shop',
        name: 'Shoe repair shop',
        nameFr: 'Shoe repair shop',
        nameEn: 'Shoe repair shop',
        icon: '🔧',
        googleBusinessCategory: 'Shoe repair shop',
      },
    ],
  },
  {
    slug: 'beaute-bien-etre',
    name: 'Beauté & Bien-être',
    nameFr: 'Beauté & Bien-être',
    nameEn: 'Beauty & Wellness',
    nameDe: 'Schönheit & Wellness',
    description: 'Salons de coiffure, spas et soins esthétiques',
    icon: '💇',
    color: '#EC4899',
    googleBusinessCategory: 'Beauty & Wellness',
    children: [
      {
        slug: 'hair-salon',
        name: 'Salon de coiffure',
        nameFr: 'Salon de coiffure',
        nameEn: 'Hair salon',
        icon: '💇',
        googleBusinessCategory: 'Hair salon',
      },
      {
        slug: 'barber-shop',
        name: 'Barbier',
        nameFr: 'Barbier',
        nameEn: 'Barber shop',
        icon: '💇',
        googleBusinessCategory: 'Barber shop',
      },
      {
        slug: 'beauty-salon',
        name: 'Salon de beauté',
        nameFr: 'Salon de beauté',
        nameEn: 'Beauty salon',
        icon: '💇',
        googleBusinessCategory: 'Beauty salon',
      },
      {
        slug: 'nail-salon',
        name: 'Salon de manucure',
        nameFr: 'Salon de manucure',
        nameEn: 'Nail salon',
        icon: '💇',
        googleBusinessCategory: 'Nail salon',
      },
      {
        slug: 'spa',
        name: 'Spa',
        nameFr: 'Spa',
        nameEn: 'Spa',
        icon: '💇',
        googleBusinessCategory: 'Spa',
      },
      {
        slug: 'massage-therapist',
        name: 'Masseur',
        nameFr: 'Masseur',
        nameEn: 'Massage therapist',
        icon: '💇',
        googleBusinessCategory: 'Massage therapist',
      },
      {
        slug: 'tanning-salon',
        name: 'Tanning salon',
        nameFr: 'Tanning salon',
        nameEn: 'Tanning salon',
        icon: '💇',
        googleBusinessCategory: 'Tanning salon',
      },
      {
        slug: 'tattoo-shop',
        name: 'Tattoo shop',
        nameFr: 'Tattoo shop',
        nameEn: 'Tattoo shop',
        icon: '💇',
        googleBusinessCategory: 'Tattoo shop',
      },
      {
        slug: 'cosmetics-store',
        name: 'Cosmetics store',
        nameFr: 'Cosmetics store',
        nameEn: 'Cosmetics store',
        icon: '💇',
        googleBusinessCategory: 'Cosmetics store',
      },
      {
        slug: 'perfume-store',
        name: 'Perfume store',
        nameFr: 'Perfume store',
        nameEn: 'Perfume store',
        icon: '💇',
        googleBusinessCategory: 'Perfume store',
      },
    ],
  },
  {
    slug: 'automobile',
    name: 'Automobile',
    nameFr: 'Automobile',
    nameEn: 'Automotive',
    nameDe: 'Automobil',
    description: 'Concessionnaires, garages et services automobiles',
    icon: '🚗',
    color: '#EF4444',
    googleBusinessCategory: 'Automotive',
    children: [
      {
        slug: 'car-dealer',
        name: 'Concessionnaire automobile',
        nameFr: 'Concessionnaire automobile',
        nameEn: 'Car dealer',
        icon: '🚗',
        googleBusinessCategory: 'Car dealer',
      },
      {
        slug: 'used-car-dealer',
        name: 'Concessionnaire de voitures d\'occasion',
        nameFr: 'Concessionnaire de voitures d\'occasion',
        nameEn: 'Used car dealer',
        icon: '🚗',
        googleBusinessCategory: 'Used car dealer',
      },
      {
        slug: 'auto-repair-shop',
        name: 'Garage automobile',
        nameFr: 'Garage automobile',
        nameEn: 'Auto repair shop',
        icon: '🚗',
        googleBusinessCategory: 'Auto repair shop',
      },
      {
        slug: 'car-wash',
        name: 'Lavage auto',
        nameFr: 'Lavage auto',
        nameEn: 'Car wash',
        icon: '🚗',
        googleBusinessCategory: 'Car wash',
      },
      {
        slug: 'auto-parts-store',
        name: 'Magasin de pièces auto',
        nameFr: 'Magasin de pièces auto',
        nameEn: 'Auto parts store',
        icon: '🚗',
        googleBusinessCategory: 'Auto parts store',
      },
      {
        slug: 'tire-shop',
        name: 'Magasin de pneus',
        nameFr: 'Magasin de pneus',
        nameEn: 'Tire shop',
        icon: '🚗',
        googleBusinessCategory: 'Tire shop',
      },
      {
        slug: 'auto-body-shop',
        name: 'Auto body shop',
        nameFr: 'Auto body shop',
        nameEn: 'Auto body shop',
        icon: '🚗',
        googleBusinessCategory: 'Auto body shop',
      },
      {
        slug: 'oil-change-service',
        name: 'Oil change service',
        nameFr: 'Oil change service',
        nameEn: 'Oil change service',
        icon: '🚗',
        googleBusinessCategory: 'Oil change service',
      },
      {
        slug: 'car-rental-agency',
        name: 'Car rental agency',
        nameFr: 'Car rental agency',
        nameEn: 'Car rental agency',
        icon: '🚗',
        googleBusinessCategory: 'Car rental agency',
      },
      {
        slug: 'gas-station',
        name: 'Station-service',
        nameFr: 'Station-service',
        nameEn: 'Gas station',
        icon: '🚗',
        googleBusinessCategory: 'Gas station',
      },
      {
        slug: 'electric-vehicle-charging-station',
        name: 'Electric vehicle charging station',
        nameFr: 'Electric vehicle charging station',
        nameEn: 'Electric vehicle charging station',
        icon: '🚗',
        googleBusinessCategory: 'Electric vehicle charging station',
      },
      {
        slug: 'motorcycle-dealer',
        name: 'Motorcycle dealer',
        nameFr: 'Motorcycle dealer',
        nameEn: 'Motorcycle dealer',
        icon: '🚗',
        googleBusinessCategory: 'Motorcycle dealer',
      },
      {
        slug: 'motorcycle-repair-shop',
        name: 'Motorcycle repair shop',
        nameFr: 'Motorcycle repair shop',
        nameEn: 'Motorcycle repair shop',
        icon: '🚗',
        googleBusinessCategory: 'Motorcycle repair shop',
      },
    ],
  },
  {
    slug: 'finance-juridique',
    name: 'Finance & Juridique',
    nameFr: 'Finance & Juridique',
    nameEn: 'Finance & Legal',
    nameDe: 'Finanzen & Recht',
    description: 'Banques, assurances, avocats et services financiers',
    icon: '💼',
    color: '#6366F1',
    googleBusinessCategory: 'Finance & Legal',
    children: [
      {
        slug: 'bank',
        name: 'Banque',
        nameFr: 'Banque',
        nameEn: 'Bank',
        icon: '💼',
        googleBusinessCategory: 'Bank',
      },
      {
        slug: 'atm',
        name: 'Distributeur automatique',
        nameFr: 'Distributeur automatique',
        nameEn: 'ATM',
        icon: '💼',
        googleBusinessCategory: 'ATM',
      },
      {
        slug: 'accountant',
        name: 'Comptable',
        nameFr: 'Comptable',
        nameEn: 'Accountant',
        icon: '💼',
        googleBusinessCategory: 'Accountant',
      },
      {
        slug: 'tax-preparation-service',
        name: 'Tax preparation service',
        nameFr: 'Tax preparation service',
        nameEn: 'Tax preparation service',
        icon: '💼',
        googleBusinessCategory: 'Tax preparation service',
      },
      {
        slug: 'insurance-agency',
        name: 'Agence d\'assurance',
        nameFr: 'Agence d\'assurance',
        nameEn: 'Insurance agency',
        icon: '💼',
        googleBusinessCategory: 'Insurance agency',
      },
      {
        slug: 'financial-planner',
        name: 'Financial planner',
        nameFr: 'Financial planner',
        nameEn: 'Financial planner',
        icon: '💼',
        googleBusinessCategory: 'Financial planner',
      },
      {
        slug: 'lawyer',
        name: 'Avocat',
        nameFr: 'Avocat',
        nameEn: 'Lawyer',
        icon: '💼',
        googleBusinessCategory: 'Lawyer',
      },
      {
        slug: 'notary-public',
        name: 'Notary public',
        nameFr: 'Notary public',
        nameEn: 'Notary public',
        icon: '💼',
        googleBusinessCategory: 'Notary public',
      },
      {
        slug: 'real-estate-agency',
        name: 'Agence immobilière',
        nameFr: 'Agence immobilière',
        nameEn: 'Real estate agency',
        icon: '💼',
        googleBusinessCategory: 'Real estate agency',
      },
    ],
  },
  {
    slug: 'education',
    name: 'Éducation',
    nameFr: 'Éducation',
    nameEn: 'Education',
    nameDe: 'Bildung',
    description: 'Établissements d'enseignement et formation',
    icon: '📚',
    color: '#06B6D4',
    googleBusinessCategory: 'Education',
    children: [
      {
        slug: 'school',
        name: 'École',
        nameFr: 'École',
        nameEn: 'School',
        icon: '📚',
        googleBusinessCategory: 'School',
      },
      {
        slug: 'primary-school',
        name: 'École primaire',
        nameFr: 'École primaire',
        nameEn: 'Primary school',
        icon: '📚',
        googleBusinessCategory: 'Primary school',
      },
      {
        slug: 'high-school',
        name: 'Lycée',
        nameFr: 'Lycée',
        nameEn: 'High school',
        icon: '📚',
        googleBusinessCategory: 'High school',
      },
      {
        slug: 'university',
        name: 'Université',
        nameFr: 'Université',
        nameEn: 'University',
        icon: '📚',
        googleBusinessCategory: 'University',
      },
      {
        slug: 'college',
        name: 'Collège',
        nameFr: 'Collège',
        nameEn: 'College',
        icon: '📚',
        googleBusinessCategory: 'College',
      },
      {
        slug: 'preschool',
        name: 'Maternelle',
        nameFr: 'Maternelle',
        nameEn: 'Preschool',
        icon: '📚',
        googleBusinessCategory: 'Preschool',
      },
      {
        slug: 'driving-school',
        name: 'Auto-école',
        nameFr: 'Auto-école',
        nameEn: 'Driving school',
        icon: '📚',
        googleBusinessCategory: 'Driving school',
      },
      {
        slug: 'language-school',
        name: 'Language school',
        nameFr: 'Language school',
        nameEn: 'Language school',
        icon: '📚',
        googleBusinessCategory: 'Language school',
      },
      {
        slug: 'music-school',
        name: 'Music school',
        nameFr: 'Music school',
        nameEn: 'Music school',
        icon: '📚',
        googleBusinessCategory: 'Music school',
      },
      {
        slug: 'dance-school',
        name: 'Dance school',
        nameFr: 'Dance school',
        nameEn: 'Dance school',
        icon: '📚',
        googleBusinessCategory: 'Dance school',
      },
      {
        slug: 'art-school',
        name: 'Art school',
        nameFr: 'Art school',
        nameEn: 'Art school',
        icon: '📚',
        googleBusinessCategory: 'Art school',
      },
      {
        slug: 'tutoring-service',
        name: 'Tutoring service',
        nameFr: 'Tutoring service',
        nameEn: 'Tutoring service',
        icon: '📚',
        googleBusinessCategory: 'Tutoring service',
      },
      {
        slug: 'library',
        name: 'Bibliothèque',
        nameFr: 'Bibliothèque',
        nameEn: 'Library',
        icon: '📚',
        googleBusinessCategory: 'Library',
      },
    ],
  },
  {
    slug: 'loisirs',
    name: 'Loisirs',
    nameFr: 'Loisirs',
    nameEn: 'Entertainment & Leisure',
    nameDe: 'Unterhaltung',
    description: 'Activités de loisirs et divertissement',
    icon: '🎭',
    color: '#F97316',
    googleBusinessCategory: 'Entertainment & Leisure',
    children: [
      {
        slug: 'movie-theater',
        name: 'Cinéma',
        nameFr: 'Cinéma',
        nameEn: 'Movie theater',
        icon: '🎭',
        googleBusinessCategory: 'Movie theater',
      },
      {
        slug: 'museum',
        name: 'Musée',
        nameFr: 'Musée',
        nameEn: 'Museum',
        icon: '🎭',
        googleBusinessCategory: 'Museum',
      },
      {
        slug: 'art-gallery',
        name: 'Galerie d\'art',
        nameFr: 'Galerie d\'art',
        nameEn: 'Art gallery',
        icon: '🎭',
        googleBusinessCategory: 'Art gallery',
      },
      {
        slug: 'zoo',
        name: 'Zoo',
        nameFr: 'Zoo',
        nameEn: 'Zoo',
        icon: '🎭',
        googleBusinessCategory: 'Zoo',
      },
      {
        slug: 'aquarium',
        name: 'Aquarium',
        nameFr: 'Aquarium',
        nameEn: 'Aquarium',
        icon: '🎭',
        googleBusinessCategory: 'Aquarium',
      },
      {
        slug: 'amusement-park',
        name: 'Parc d\'attractions',
        nameFr: 'Parc d\'attractions',
        nameEn: 'Amusement park',
        icon: '🎭',
        googleBusinessCategory: 'Amusement park',
      },
      {
        slug: 'bowling-alley',
        name: 'Bowling alley',
        nameFr: 'Bowling alley',
        nameEn: 'Bowling alley',
        icon: '🎭',
        googleBusinessCategory: 'Bowling alley',
      },
      {
        slug: 'gym',
        name: 'Salle de sport',
        nameFr: 'Salle de sport',
        nameEn: 'Gym',
        icon: '🎭',
        googleBusinessCategory: 'Gym',
      },
      {
        slug: 'yoga-studio',
        name: 'Studio de yoga',
        nameFr: 'Studio de yoga',
        nameEn: 'Yoga studio',
        icon: '🎭',
        googleBusinessCategory: 'Yoga studio',
      },
      {
        slug: 'sports-club',
        name: 'Sports club',
        nameFr: 'Sports club',
        nameEn: 'Sports club',
        icon: '🎭',
        googleBusinessCategory: 'Sports club',
      },
      {
        slug: 'swimming-pool',
        name: 'Swimming pool',
        nameFr: 'Swimming pool',
        nameEn: 'Swimming pool',
        icon: '🎭',
        googleBusinessCategory: 'Swimming pool',
      },
      {
        slug: 'golf-course',
        name: 'Golf course',
        nameFr: 'Golf course',
        nameEn: 'Golf course',
        icon: '🎭',
        googleBusinessCategory: 'Golf course',
      },
      {
        slug: 'park',
        name: 'Parc',
        nameFr: 'Parc',
        nameEn: 'Park',
        icon: '🎭',
        googleBusinessCategory: 'Park',
      },
      {
        slug: 'playground',
        name: 'Playground',
        nameFr: 'Playground',
        nameEn: 'Playground',
        icon: '🎭',
        googleBusinessCategory: 'Playground',
      },
      {
        slug: 'tourist-attraction',
        name: 'Tourist attraction',
        nameFr: 'Tourist attraction',
        nameEn: 'Tourist attraction',
        icon: '🎭',
        googleBusinessCategory: 'Tourist attraction',
      },
    ],
  },
  {
    slug: 'hebergement',
    name: 'Hébergement',
    nameFr: 'Hébergement',
    nameEn: 'Lodging',
    nameDe: 'Unterkunft',
    description: 'Hôtels et hébergements',
    icon: '🏨',
    color: '#14B8A6',
    googleBusinessCategory: 'Lodging',
    children: [
      {
        slug: 'hotel',
        name: 'Hôtel',
        nameFr: 'Hôtel',
        nameEn: 'Hotel',
        icon: '🏨',
        googleBusinessCategory: 'Hotel',
      },
      {
        slug: 'motel',
        name: 'Motel',
        nameFr: 'Motel',
        nameEn: 'Motel',
        icon: '🏨',
        googleBusinessCategory: 'Motel',
      },
      {
        slug: 'hostel',
        name: 'Auberge de jeunesse',
        nameFr: 'Auberge de jeunesse',
        nameEn: 'Hostel',
        icon: '🏨',
        googleBusinessCategory: 'Hostel',
      },
      {
        slug: 'bed-&-breakfast',
        name: 'Chambre d\'hôtes',
        nameFr: 'Chambre d\'hôtes',
        nameEn: 'Bed & breakfast',
        icon: '🏨',
        googleBusinessCategory: 'Bed & breakfast',
      },
      {
        slug: 'extended-stay-hotel',
        name: 'Extended stay hotel',
        nameFr: 'Extended stay hotel',
        nameEn: 'Extended stay hotel',
        icon: '🏨',
        googleBusinessCategory: 'Extended stay hotel',
      },
      {
        slug: 'vacation-home-rental-agency',
        name: 'Vacation home rental agency',
        nameFr: 'Vacation home rental agency',
        nameEn: 'Vacation home rental agency',
        icon: '🏨',
        googleBusinessCategory: 'Vacation home rental agency',
      },
      {
        slug: 'campground',
        name: 'Campground',
        nameFr: 'Campground',
        nameEn: 'Campground',
        icon: '🏨',
        googleBusinessCategory: 'Campground',
      },
      {
        slug: 'rv-park',
        name: 'RV park',
        nameFr: 'RV park',
        nameEn: 'RV park',
        icon: '🏨',
        googleBusinessCategory: 'RV park',
      },
    ],
  },
];

async function seedCategory(
  categoryData: CategoryData,
  parentId: number | null = null,
  order: number = 0
) {
  console.log(`Creating category: ${categoryData.nameFr} (parent: ${parentId})`);

  const category = await prisma.category.create({
    data: {
      slug: categoryData.slug,
      name: categoryData.name,
      nameFr: categoryData.nameFr,
      nameEn: categoryData.nameEn,
      nameDe: categoryData.nameDe,
      description: categoryData.description,
      icon: categoryData.icon,
      color: categoryData.color,
      parentId: parentId,
      googleTypes: categoryData.googleTypes || [],
      googleBusinessCategory: categoryData.googleBusinessCategory,
      isActive: true,
      order: order,
    },
  });

  // Recursively create children
  if (categoryData.children) {
    for (let i = 0; i < categoryData.children.length; i++) {
      await seedCategory(categoryData.children[i], category.id, i);
    }
  }

  return category;
}

async function main() {
  console.log('🌱 Starting enhanced category hierarchy seed...');
  console.log('📊 Total categories: 227+ (10 parent + 217+ children)');

  // Delete existing categories (cascade will delete company_categories too)
  await prisma.category.deleteMany();
  console.log('✅ Deleted existing categories');

  // Create all parent categories and their children
  for (let i = 0; i < categories.length; i++) {
    await seedCategory(categories[i], null, i);
  }

  console.log('✅ Enhanced category hierarchy seeded successfully!');

  // Print summary
  const totalCategories = await prisma.category.count();
  const parentCategories = await prisma.category.count({
    where: { parentId: null },
  });
  const childCategories = await prisma.category.count({
    where: { parentId: { not: null } },
  });

  console.log(`
📊 Summary:
- Total categories: ${totalCategories}
- Parent categories: ${parentCategories}
- Child categories: ${childCategories}
  `);

  // Display all categories with hierarchy
  const allCategories = await prisma.category.findMany({
    where: { parentId: null },
    include: {
      children: {
        orderBy: { order: 'asc' },
      },
    },
    orderBy: { order: 'asc' },
  });

  console.log('\n📁 Category Hierarchy:');
  allCategories.forEach((parent) => {
    console.log(`\n${parent.icon} ${parent.nameFr} (${parent.children.length} subcategories)`);
    parent.children.slice(0, 5).forEach((child) => {
      console.log(`  ├─ ${child.icon} ${child.nameFr}`);
    });
    if (parent.children.length > 5) {
      console.log(`  └─ ... and ${parent.children.length - 5} more`);
    }
  });
}

main()
  .catch((e) => {
    console.error('❌ Error seeding categories:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
