import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

async function main() {
  console.log('🏢 Starting companies seed for remaining 8 cities...\n');

  const domains = await prisma.domain.findMany();
  console.log(`Found ${domains.length} domains\n`);

  const citiesData: Record<string, any[]> = {
    'ingwiller.pro': [
      {
        name: 'Restaurant À la Couronne',
        address: '10 Rue du Général de Gaulle',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 40 12',
        email: 'contact@lacouronne-ingwiller.fr',
        categories: ['Restaurant', 'Cuisine Alsacienne'],
      },
      {
        name: 'Boulangerie Pâtisserie Wolff',
        address: '18 Grand Rue',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 41 45',
        email: 'boulangerie.wolff@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie de la Ville',
        address: '12 Place de la Mairie',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 42 78',
        email: 'pharmacie.ingwiller@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Renault Ingwiller Auto',
        address: '25 Route de Bouxwiller',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 43 91',
        email: 'ingwiller.auto@wanadoo.fr',
        website: 'https://ingwiller-auto.fr',
        categories: ['Garage', 'Automobile', 'Renault'],
      },
      {
        name: 'Coiffure Création',
        address: '14 Grand Rue',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 44 23',
        email: 'creation.coiffure@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Traiteur Schmitt',
        address: '21 Rue Principale',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 45 56',
        email: 'boucherie.schmitt@orange.fr',
        categories: ['Boucherie', 'Charcuterie', 'Traiteur'],
      },
      {
        name: 'Cabinet Dentaire Dr. Keller',
        address: '6 Rue de la Santé',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 46 89',
        email: 'dr.keller.dentiste@gmail.com',
        categories: ['Dentiste', 'Santé'],
      },
      {
        name: 'Fleuriste Au Jardin des Fleurs',
        address: '8 Place de la Mairie',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 47 12',
        email: 'jardin.fleurs@gmail.com',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria Bella Italia',
        address: '23 Grand Rue',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 48 45',
        email: 'bella.italia.ingwiller@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Journaux',
        address: '16 Rue Principale',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 49 78',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Agence Immobilière Nord Alsace',
        address: '19 Grand Rue',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 50 91',
        email: 'contact@nordalsace-immo.fr',
        website: 'https://nordalsace-immo.fr',
        categories: ['Immobilier', 'Agence'],
      },
      {
        name: 'Banque Populaire',
        address: '11 Place de la Mairie',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 51 23',
        website: 'https://www.banquepopulaire.fr',
        categories: ['Banque', 'Finance'],
      },
      {
        name: 'Supermarché Proxi',
        address: '32 Route de Bouxwiller',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 52 56',
        categories: ['Supermarché', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Café Bar Le Central',
        address: '5 Place de la Mairie',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 53 89',
        categories: ['Café', 'Bar'],
      },
      {
        name: 'Électricité Plomberie Muller',
        address: '28 Rue de l\'Artisanat',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 54 12',
        email: 'muller.electricite@orange.fr',
        categories: ['Électricité', 'Plomberie', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Marc Dubois',
        address: '7 Rue de la Santé',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 55 45',
        email: 'marc.dubois.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Optique Vision Ingwiller',
        address: '15 Grand Rue',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 56 78',
        email: 'optique.vision.ingwiller@gmail.com',
        categories: ['Optique', 'Santé'],
      },
      {
        name: 'Menuiserie Bois & Tradition',
        address: '30 Route de Bouxwiller',
        city: 'Ingwiller',
        postalCode: '67340',
        phone: '+33 3 88 89 57 91',
        email: 'bois.tradition@orange.fr',
        categories: ['Menuiserie', 'Artisan'],
      },
    ],

    'saverne.pro': [
      {
        name: 'Restaurant Le Château',
        address: '15 Rue du Château',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 10 12',
        email: 'contact@lechateau-saverne.fr',
        website: 'https://lechateau-saverne.fr',
        categories: ['Restaurant', 'Gastronomie'],
      },
      {
        name: 'Boulangerie Pâtisserie Chez Paul',
        address: '28 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 11 45',
        email: 'chezpaul.saverne@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie Principale',
        address: '22 Place de la Gare',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 12 78',
        email: 'pharmacie.principale.saverne@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Citroën Saverne Motors',
        address: '45 Route de Strasbourg',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 13 91',
        email: 'contact@saverne-motors.fr',
        website: 'https://saverne-motors.fr',
        categories: ['Garage', 'Automobile', 'Citroën'],
      },
      {
        name: 'Coiffure Élégance & Style',
        address: '19 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 14 23',
        email: 'elegance.style@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Wagner',
        address: '31 Rue du Marché',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 15 56',
        email: 'boucherie.wagner@wanadoo.fr',
        categories: ['Boucherie', 'Charcuterie'],
      },
      {
        name: 'Cabinet Médical Centre Santé',
        address: '12 Rue de la Santé',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 16 89',
        email: 'centre.sante.saverne@gmail.com',
        categories: ['Médecin', 'Santé'],
      },
      {
        name: 'Fleuriste Les Roses de Saverne',
        address: '9 Place du Marché',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 17 12',
        email: 'roses.saverne@orange.fr',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria Napoli',
        address: '26 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 18 45',
        email: 'napoli.saverne@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Le Kiosque',
        address: '18 Place de la Gare',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 19 78',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Agence Immobilière Saverne Habitat',
        address: '24 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 20 91',
        email: 'contact@saverne-habitat.fr',
        website: 'https://saverne-habitat.fr',
        categories: ['Immobilier', 'Agence'],
      },
      {
        name: 'Banque LCL',
        address: '16 Place de la République',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 21 23',
        website: 'https://www.lcl.fr',
        categories: ['Banque', 'Finance'],
      },
      {
        name: 'Supermarché Auchan',
        address: '52 Route de Strasbourg',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 22 56',
        website: 'https://www.auchan.fr',
        categories: ['Supermarché', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Café Brasserie Le Rohan',
        address: '7 Place du Château',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 23 89',
        categories: ['Café', 'Brasserie', 'Restaurant'],
      },
      {
        name: 'Plomberie Chauffage Sanitaire Klein',
        address: '33 Rue de l\'Industrie',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 24 12',
        email: 'klein.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Sophie Martin',
        address: '11 Rue de la Santé',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 25 45',
        email: 'sophie.martin.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Optique Alain Afflelou',
        address: '21 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 26 78',
        website: 'https://www.alainafflelou.com',
        categories: ['Optique', 'Santé'],
      },
      {
        name: 'Auto-École Permis Plus',
        address: '17 Place de la Gare',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 27 91',
        email: 'permis.plus.saverne@gmail.com',
        categories: ['Auto-École', 'Formation'],
      },
      {
        name: 'Vétérinaire Clinique Vétérinaire',
        address: '38 Route de Strasbourg',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 28 23',
        email: 'clinique.veterinaire.saverne@orange.fr',
        categories: ['Vétérinaire', 'Santé Animale'],
      },
      {
        name: 'Librairie Papeterie Le Livre',
        address: '14 Grand Rue',
        city: 'Saverne',
        postalCode: '67700',
        phone: '+33 3 88 91 29 56',
        email: 'librairie.lelivre@wanadoo.fr',
        categories: ['Librairie', 'Papeterie', 'Commerce'],
      },
    ],

    'schiltigheim.pro': [
      {
        name: 'Brasserie Schutzenberger',
        address: '8 Rue de la Brasserie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 60 12',
        email: 'contact@schutzenberger.fr',
        website: 'https://schutzenberger.fr',
        categories: ['Brasserie', 'Industrie', 'Bière'],
      },
      {
        name: 'Restaurant Au Bœuf Mode',
        address: '22 Route de Bischwiller',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 61 45',
        email: 'contact@boeufmode.fr',
        categories: ['Restaurant', 'Cuisine Française'],
      },
      {
        name: 'Boulangerie Pâtisserie Artisanale',
        address: '35 Route du Général de Gaulle',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 62 78',
        email: 'boulangerie.artisanale@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie de la Mairie',
        address: '18 Place de la Mairie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 63 91',
        email: 'pharmacie.mairie.schiltigheim@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Ford Schiltigheim Auto',
        address: '42 Route de Strasbourg',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 64 23',
        email: 'schiltigheim.auto@wanadoo.fr',
        website: 'https://schiltigheim-auto.fr',
        categories: ['Garage', 'Automobile', 'Ford'],
      },
      {
        name: 'Coiffure Tendance & Beauté',
        address: '27 Route du Général de Gaulle',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 65 56',
        email: 'tendance.beaute@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Traiteur Fuchs',
        address: '31 Route de Bischwiller',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 66 89',
        email: 'boucherie.fuchs@orange.fr',
        categories: ['Boucherie', 'Charcuterie', 'Traiteur'],
      },
      {
        name: 'Cabinet Dentaire Dr. Schneider',
        address: '14 Rue de la Santé',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 67 12',
        email: 'dr.schneider.dentiste@gmail.com',
        categories: ['Dentiste', 'Santé'],
      },
      {
        name: 'Fleuriste Au Bouquet de Schiltigheim',
        address: '11 Place de la Mairie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 68 45',
        email: 'bouquet.schiltigheim@gmail.com',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria Da Vinci',
        address: '29 Route du Général de Gaulle',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 69 78',
        email: 'davinci.schiltigheim@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Loto Central',
        address: '19 Place de la Mairie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 70 91',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Agence Immobilière Schiltigheim Immobilier',
        address: '25 Route du Général de Gaulle',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 71 23',
        email: 'contact@schiltigheim-immobilier.fr',
        website: 'https://schiltigheim-immobilier.fr',
        categories: ['Immobilier', 'Agence'],
      },
      {
        name: 'Banque Société Générale',
        address: '16 Place de la République',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 72 56',
        website: 'https://www.societegenerale.fr',
        categories: ['Banque', 'Finance'],
      },
      {
        name: 'Supermarché Lidl',
        address: '48 Route de Strasbourg',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 73 89',
        website: 'https://www.lidl.fr',
        categories: ['Supermarché', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Café Bar Le Strasbourg',
        address: '9 Place de la Mairie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 74 12',
        categories: ['Café', 'Bar'],
      },
      {
        name: 'Plomberie Chauffage Hoffmann',
        address: '36 Rue de l\'Industrie',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 75 45',
        email: 'hoffmann.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Jean Dupont',
        address: '13 Rue de la Santé',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 76 78',
        email: 'jean.dupont.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Optique Grand Optical',
        address: '23 Route du Général de Gaulle',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 77 91',
        website: 'https://www.grandoptical.com',
        categories: ['Optique', 'Santé'],
      },
      {
        name: 'Pressing Laverie Moderne',
        address: '28 Route de Bischwiller',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 78 23',
        categories: ['Pressing', 'Laverie', 'Services'],
      },
      {
        name: 'Vétérinaire Cabinet Vétérinaire',
        address: '41 Route de Strasbourg',
        city: 'Schiltigheim',
        postalCode: '67300',
        phone: '+33 3 88 18 79 56',
        email: 'cabinet.veterinaire.schiltigheim@orange.fr',
        categories: ['Vétérinaire', 'Santé Animale'],
      },
    ],

    'schweighouse.pro': [
      {
        name: 'Restaurant Au Cheval Blanc',
        address: '12 Grand Rue',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 80 12',
        email: 'contact@chevalblanc-schweighouse.fr',
        categories: ['Restaurant', 'Cuisine Alsacienne'],
      },
      {
        name: 'Boulangerie Pâtisserie Lehmann',
        address: '18 Rue Principale',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 81 45',
        email: 'boulangerie.lehmann@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie du Village',
        address: '8 Place de l\'Église',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 82 78',
        email: 'pharmacie.schweighouse@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Automobile Roth',
        address: '25 Route de Haguenau',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 83 91',
        email: 'garage.roth@wanadoo.fr',
        categories: ['Garage', 'Automobile', 'Réparation'],
      },
      {
        name: 'Coiffure Salon Moderne',
        address: '14 Grand Rue',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 84 23',
        email: 'salon.moderne@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Muller',
        address: '21 Rue Principale',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 85 56',
        email: 'boucherie.muller@orange.fr',
        categories: ['Boucherie', 'Charcuterie'],
      },
      {
        name: 'Cabinet Médical Dr. Weber',
        address: '6 Rue de la Santé',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 86 89',
        email: 'dr.weber@medecin-schweighouse.fr',
        categories: ['Médecin', 'Santé'],
      },
      {
        name: 'Fleuriste Les Jardins Fleuris',
        address: '9 Place de l\'Église',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 87 12',
        email: 'jardins.fleuris@gmail.com',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria La Bella',
        address: '23 Grand Rue',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 88 45',
        email: 'labella.schweighouse@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Loto',
        address: '16 Rue Principale',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 89 78',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Épicerie Alimentation Générale',
        address: '11 Grand Rue',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 90 91',
        categories: ['Épicerie', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Plomberie Chauffage Schneider',
        address: '28 Route de Haguenau',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 91 23',
        email: 'schneider.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Marie Laurent',
        address: '7 Rue de la Santé',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 92 56',
        email: 'marie.laurent.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Menuiserie Bois & Création',
        address: '30 Route de Haguenau',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 93 89',
        email: 'bois.creation@orange.fr',
        categories: ['Menuiserie', 'Artisan'],
      },
      {
        name: 'Café Restaurant Le Village',
        address: '10 Place de l\'Église',
        city: 'Schweighouse-sur-Moder',
        postalCode: '67590',
        phone: '+33 3 88 72 94 12',
        categories: ['Café', 'Restaurant'],
      },
    ],

    'souffelweyersheim.pro': [
      {
        name: 'Restaurant La Table Gourmande',
        address: '15 Rue du Général Leclerc',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 10 12',
        email: 'contact@tablegourmande.fr',
        website: 'https://tablegourmande-souffelweyersheim.fr',
        categories: ['Restaurant', 'Gastronomie'],
      },
      {
        name: 'Boulangerie Pâtisserie Artisanale Kieffer',
        address: '28 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 11 45',
        email: 'boulangerie.kieffer@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie Centrale',
        address: '22 Place de la Mairie',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 12 78',
        email: 'pharmacie.centrale.souffel@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Volkswagen Souffel Auto',
        address: '42 Route de Strasbourg',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 13 91',
        email: 'contact@souffel-auto.fr',
        website: 'https://souffel-auto.fr',
        categories: ['Garage', 'Automobile', 'Volkswagen'],
      },
      {
        name: 'Coiffure Studio Élégance',
        address: '19 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 14 23',
        email: 'studio.elegance@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Traiteur Klein',
        address: '31 Rue du Marché',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 15 56',
        email: 'boucherie.klein@wanadoo.fr',
        categories: ['Boucherie', 'Charcuterie', 'Traiteur'],
      },
      {
        name: 'Cabinet Dentaire Dr. Hoffmann',
        address: '12 Rue de la Santé',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 16 89',
        email: 'dr.hoffmann.dentiste@gmail.com',
        categories: ['Dentiste', 'Santé'],
      },
      {
        name: 'Fleuriste Au Jardin des Roses',
        address: '9 Place de la Mairie',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 17 12',
        email: 'jardin.roses@orange.fr',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria Bella Vita',
        address: '26 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 18 45',
        email: 'bellavita.souffel@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Le Kiosque',
        address: '18 Rue du Général Leclerc',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 19 78',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Agence Immobilière Souffel Habitat',
        address: '24 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 20 91',
        email: 'contact@souffel-habitat.fr',
        website: 'https://souffel-habitat.fr',
        categories: ['Immobilier', 'Agence'],
      },
      {
        name: 'Banque BNP Paribas',
        address: '16 Place de la République',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 21 23',
        website: 'https://www.bnpparibas.fr',
        categories: ['Banque', 'Finance'],
      },
      {
        name: 'Supermarché Cora',
        address: '48 Route de Strasbourg',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 22 56',
        website: 'https://www.cora.fr',
        categories: ['Supermarché', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Café Brasserie Le Central',
        address: '7 Place de la Mairie',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 23 89',
        categories: ['Café', 'Brasserie', 'Restaurant'],
      },
      {
        name: 'Plomberie Chauffage Sanitaire Fuchs',
        address: '33 Rue de l\'Industrie',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 24 12',
        email: 'fuchs.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Anne Dubois',
        address: '11 Rue de la Santé',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 25 45',
        email: 'anne.dubois.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Optique Optic 2000',
        address: '21 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 26 78',
        website: 'https://www.optic2000.com',
        categories: ['Optique', 'Santé'],
      },
      {
        name: 'Auto-École Conduite Moderne',
        address: '17 Rue du Général Leclerc',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 27 91',
        email: 'conduite.moderne@gmail.com',
        categories: ['Auto-École', 'Formation'],
      },
      {
        name: 'Vétérinaire Clinique Vétérinaire du Kochersberg',
        address: '38 Route de Strasbourg',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 28 23',
        email: 'clinique.veterinaire.kochersberg@orange.fr',
        categories: ['Vétérinaire', 'Santé Animale'],
      },
      {
        name: 'Pressing Laverie Express',
        address: '29 Avenue de la Liberté',
        city: 'Souffelweyersheim',
        postalCode: '67460',
        phone: '+33 3 88 20 29 56',
        categories: ['Pressing', 'Laverie', 'Services'],
      },
    ],

    'soufflenheim.pro': [
      {
        name: 'Restaurant Au Bœuf',
        address: '12 Grand Rue',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 60 12',
        email: 'contact@auboeuf-soufflenheim.fr',
        categories: ['Restaurant', 'Cuisine Alsacienne'],
      },
      {
        name: 'Boulangerie Pâtisserie Schmitt',
        address: '18 Rue de la Poterie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 61 45',
        email: 'boulangerie.schmitt@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie du Village',
        address: '8 Place de la Mairie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 62 78',
        email: 'pharmacie.soufflenheim@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Automobile Fischer',
        address: '25 Route de Haguenau',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 63 91',
        email: 'garage.fischer@wanadoo.fr',
        categories: ['Garage', 'Automobile', 'Réparation'],
      },
      {
        name: 'Coiffure Beauté Création',
        address: '14 Grand Rue',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 64 23',
        email: 'beaute.creation@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Poterie d\'Alsace - Atelier Lehmann',
        address: '21 Rue de la Poterie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 65 56',
        email: 'poterie.lehmann@orange.fr',
        website: 'https://poterie-lehmann.fr',
        categories: ['Poterie', 'Artisanat', 'Tradition'],
      },
      {
        name: 'Poterie Traditionnelle Wehrling',
        address: '28 Rue de la Poterie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 66 89',
        email: 'poterie.wehrling@wanadoo.fr',
        website: 'https://poterie-wehrling.fr',
        categories: ['Poterie', 'Artisanat', 'Tradition'],
      },
      {
        name: 'Cabinet Médical Dr. Muller',
        address: '6 Rue de la Santé',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 67 12',
        email: 'dr.muller@medecin-soufflenheim.fr',
        categories: ['Médecin', 'Santé'],
      },
      {
        name: 'Fleuriste Les Fleurs du Jardin',
        address: '9 Place de la Mairie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 68 45',
        email: 'fleurs.jardin@gmail.com',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria La Mamma',
        address: '23 Grand Rue',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 69 78',
        email: 'lamamma.soufflenheim@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Loto',
        address: '16 Rue de la Poterie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 70 91',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Épicerie Alimentation Générale',
        address: '11 Grand Rue',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 71 23',
        categories: ['Épicerie', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Plomberie Chauffage Roth',
        address: '28 Route de Haguenau',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 72 56',
        email: 'roth.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Pierre Laurent',
        address: '7 Rue de la Santé',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 73 89',
        email: 'pierre.laurent.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Café Restaurant Le Village',
        address: '10 Place de la Mairie',
        city: 'Soufflenheim',
        postalCode: '67620',
        phone: '+33 3 88 86 74 12',
        categories: ['Café', 'Restaurant'],
      },
    ],

    'wissembourg.pro': [
      {
        name: 'Restaurant Au Cygne',
        address: '15 Rue du Général Leclerc',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 00 12',
        email: 'contact@aucygne-wissembourg.fr',
        website: 'https://aucygne-wissembourg.fr',
        categories: ['Restaurant', 'Gastronomie'],
      },
      {
        name: 'Boulangerie Pâtisserie Chez André',
        address: '28 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 01 45',
        email: 'chezandre.wissembourg@orange.fr',
        categories: ['Boulangerie', 'Pâtisserie'],
      },
      {
        name: 'Pharmacie Principale',
        address: '22 Place de la République',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 02 78',
        email: 'pharmacie.principale.wissembourg@gmail.com',
        categories: ['Pharmacie', 'Santé'],
      },
      {
        name: 'Garage Opel Wissembourg Auto',
        address: '42 Route de Strasbourg',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 03 91',
        email: 'contact@wissembourg-auto.fr',
        website: 'https://wissembourg-auto.fr',
        categories: ['Garage', 'Automobile', 'Opel'],
      },
      {
        name: 'Coiffure Salon Moderne',
        address: '19 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 04 23',
        email: 'salon.moderne.wissembourg@gmail.com',
        categories: ['Coiffure', 'Beauté'],
      },
      {
        name: 'Boucherie Charcuterie Traiteur Wagner',
        address: '31 Rue du Marché',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 05 56',
        email: 'boucherie.wagner@wanadoo.fr',
        categories: ['Boucherie', 'Charcuterie', 'Traiteur'],
      },
      {
        name: 'Cabinet Dentaire Dr. Schneider',
        address: '12 Rue de la Santé',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 06 89',
        email: 'dr.schneider.dentiste@gmail.com',
        categories: ['Dentiste', 'Santé'],
      },
      {
        name: 'Fleuriste Au Bouquet de Wissembourg',
        address: '9 Place de la République',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 07 12',
        email: 'bouquet.wissembourg@orange.fr',
        categories: ['Fleuriste', 'Décoration'],
      },
      {
        name: 'Pizzeria Venezia',
        address: '26 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 08 45',
        email: 'venezia.wissembourg@gmail.com',
        categories: ['Pizzeria', 'Restaurant', 'Italien'],
      },
      {
        name: 'Tabac Presse Le Central',
        address: '18 Rue du Général Leclerc',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 09 78',
        categories: ['Tabac', 'Presse', 'Commerce'],
      },
      {
        name: 'Agence Immobilière Wissembourg Immobilier',
        address: '24 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 10 91',
        email: 'contact@wissembourg-immobilier.fr',
        website: 'https://wissembourg-immobilier.fr',
        categories: ['Immobilier', 'Agence'],
      },
      {
        name: 'Banque Crédit Mutuel',
        address: '16 Place de la République',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 11 23',
        website: 'https://www.creditmutuel.fr',
        categories: ['Banque', 'Finance'],
      },
      {
        name: 'Supermarché Match',
        address: '48 Route de Strasbourg',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 12 56',
        website: 'https://www.supermarchesmatch.fr',
        categories: ['Supermarché', 'Alimentation', 'Commerce'],
      },
      {
        name: 'Café Brasserie Le Strasbourg',
        address: '7 Place de la République',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 13 89',
        categories: ['Café', 'Brasserie', 'Restaurant'],
      },
      {
        name: 'Plomberie Chauffage Sanitaire Hoffmann',
        address: '33 Rue de l\'Industrie',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 14 12',
        email: 'hoffmann.plomberie@orange.fr',
        categories: ['Plomberie', 'Chauffage', 'Artisan'],
      },
      {
        name: 'Kinésithérapeute Marie Dubois',
        address: '11 Rue de la Santé',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 15 45',
        email: 'marie.dubois.kine@gmail.com',
        categories: ['Kinésithérapie', 'Santé'],
      },
      {
        name: 'Optique Afflelou',
        address: '21 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 16 78',
        website: 'https://www.alainafflelou.com',
        categories: ['Optique', 'Santé'],
      },
      {
        name: 'Auto-École Permis Conduite',
        address: '17 Rue du Général Leclerc',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 17 91',
        email: 'permis.conduite.wissembourg@gmail.com',
        categories: ['Auto-École', 'Formation'],
      },
      {
        name: 'Vétérinaire Cabinet Vétérinaire du Nord',
        address: '38 Route de Strasbourg',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 18 23',
        email: 'cabinet.veterinaire.nord@orange.fr',
        categories: ['Vétérinaire', 'Santé Animale'],
      },
      {
        name: 'Librairie Papeterie Le Livre d\'Or',
        address: '14 Rue Nationale',
        city: 'Wissembourg',
        postalCode: '67160',
        phone: '+33 3 88 94 19 56',
        email: 'librairie.livredor.wissembourg@wanadoo.fr',
        categories: ['Librairie', 'Papeterie', 'Commerce'],
      },
    ],
  };

  // Process all cities
  for (const [domainName, companies] of Object.entries(citiesData)) {
    const domain = domains.find((d) => d.name === domainName);
    if (!domain) {
      console.log(`⚠️  Domain not found: ${domainName}`);
      continue;
    }

    console.log(`\n📍 Processing ${domainName} (${companies.length} companies)...`);

    for (const companyData of companies) {
      const slug = generateSlug(companyData.name);

      const existingCompany = await prisma.company.findUnique({
        where: { slug },
      });

      if (existingCompany) {
        console.log(`  ⏭️  Skipping existing: ${companyData.name}`);
        
        const existingContent = await prisma.companyContent.findFirst({
          where: {
            companyId: existingCompany.id,
            domainId: domain.id,
          },
        });

        if (!existingContent) {
          await prisma.companyContent.create({
            data: {
              companyId: existingCompany.id,
              domainId: domain.id,
              isVisible: true,
            },
          });
          console.log(`  ✅ Added content link for domain`);
        }
        continue;
      }

      const company = await prisma.company.create({
        data: {
          name: companyData.name,
          slug,
          address: companyData.address,
          city: companyData.city,
          postalCode: companyData.postalCode,
          phone: companyData.phone,
          email: companyData.email,
          website: companyData.website,
          categories: companyData.categories,
        },
      });

      await prisma.companyContent.create({
        data: {
          companyId: company.id,
          domainId: domain.id,
          isVisible: true,
        },
      });

      console.log(`  ✅ Created: ${companyData.name}`);
    }
  }

  console.log('\n✅ All remaining 8 cities companies seed completed!');
  
  const totalCompanies = await prisma.company.count();
  const totalContent = await prisma.companyContent.count();
  console.log(`\n📊 Summary:`);
  console.log(`   Total companies: ${totalCompanies}`);
  console.log(`   Total company-domain links: ${totalContent}`);
}

main()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

